# fly.toml app configuration file generated for renatofrutuoso on 2023-10-30T13:45:50-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "renatofrutuoso"
primary_region = "gru"
console_command = "/rails/bin/rails console"

[build]

[deploy]
  release_command = "./bin/rails db:migrate"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
